language: node_js
node_js:
  - node
  - 8
  - 6
git:
  depth: 5
matrix:
  allow_failures:
    - node_js: node
  fast_finish: true
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
script: npm t
after_success: codecov
